openapi: 3.0.0
info:
  title: MHCoin API
  version: '1.0'
  contact:
    name: Лапки
    url: 'https://t.me/lapkioff'
    email: contact@lapkidev.com
  license:
    name: 'MHCoin Licence '
    url: 'https://mhc.lapki.dev/'
  description: REST Api для работы с сервером MHC (переводы)
servers:
  - url: 'https://mhc.lapki.dev/api'
    description: Сервер на сайте Лапки
  - url: 'https://mhcoin.duckdns.org/api'
    description: Оригинальный сервер
paths:
  /info:
    get:
      summary: Информация о сервере и сети MHCoin
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  last_update:
                    type: number
                    description: Время последнего обновления
                  network:
                    type: object
                    description: Информация о сети
                    required:
                      - blocks
                      - difficulty
                      - total_emission
                      - users
                    properties:
                      blocks:
                        type: number
                        description: Количество блоков
                      difficulty:
                        type: number
                        description: Сложность
                      total_emission:
                        type: number
                        description: Всего монет
                      users:
                        type: number
                        description: Количество зарегестрированных пользователей
                  server:
                    type: object
                    description: Информация о сервере
                    required:
                      - cpu
                      - ram
                      - version
                    properties:
                      cpu:
                        type: number
                        description: Использование CPU
                      ram:
                        type: number
                        description: Использование RAM
                      version:
                        type: number
                        description: Версия сервера
                required:
                  - last_update
                  - network
                  - server
      operationId: get-info
      description: 'Информация о нагрузке на CPU, RAM, количество блоков, пользователей, сложности'
  /rich:
    get:
      summary: Список 10 самых богатых пользователей
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  users:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    description: Список пользователей
                    items:
                      type: object
                      description: Пользователь
                      properties:
                        balance:
                          type: number
                          description: Баланс пользователя
                        username:
                          type: string
                          minLength: 1
                          description: Ник
                      required:
                        - balance
                        - username
                required:
                  - users
      operationId: get-rich
      description: Самые богатые пользователи
  /users/login:
    post:
      summary: ''
      operationId: post-users-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  status:
                    type: string
                    minLength: 1
                    description: Статус (ok)
                  token:
                    type: string
                    minLength: 1
                    description: Токен
                required:
                  - status
                  - token
            application/xml:
              schema:
                type: object
                properties: {}
      description: |-
        Получение токена для дальнейшего взаимодействия с API

        Токен живет 24 часа

        Дальше его надо передать в Header Authorization
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                username:
                  type: string
                  minLength: 1
                  description: Ник
                password:
                  type: string
                  minLength: 1
                  description: |
                    Пароль
              required:
                - username
                - password
